### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by AndyGuo1** [yzspku/CQTNet#5]
作者您好，能提供一下SHS100K 的CQT 特征嘛。或者怎样去通过YouTube的url去生成SHS100K 的CQT 特征呢

**Comment by yzspku** [comment]
> 作者您好，能提供一下SHS100K 的CQT 特征嘛。或者怎样去通过YouTube的url去生成SHS100K 的CQT 特征呢

https://pan.baidu.com/s/1UqWabuYA2DWqV2natwmB6Q?pwd=7c93 
提取码：7c93

**Comment by AndyGuo1** [comment]
好的，非常感谢！
