### ISSUE TITLE
有关全连接层FC1的输出4611的疑问

### ISSUE THREAD

**Issue by AndyGuo1** [yzspku/CQTNet#6]
作者您好，在论文中最后的全连接层FC1设置的输出维度为4611。训练集中存在84340首歌曲，由于非连续，存在例如5982_7代表label为5982的第七首翻唱。这样训练会报IndexError: Target 5982 is out of bounds.
代码中FC1全连接层的输出维度是10000。我应该是把训练集中不连续的数据进行处理，保持FC1为4611,还是设置为10000进行训练呢。

**Comment by AndyGuo1** [comment]
![image](https://github.com/yzspku/CQTNet/assets/98161139/28a27020-efc2-43f1-96c6-41a61ea65da0)

**Comment by yzspku** [comment]
两种都可以的，不影响效果

> 作者您好，在论文中最后的全连接层FC1设置的输出维度为4611。训练集中存在84340首歌曲，由于非连续，存在例如5982_7代表label为5982的第七首翻唱。这样训练会报IndexError: Target 5982 is out of bounds. 代码中FC1全连接层的输出维度是10000。我应该是把训练集中不连续的数据进行处理，保持FC1为4611,还是设置为10000进行训练呢。

**Comment by AndyGuo1** [comment]
嗯嗯好的，感谢
